import type { InsightsResponse } from "../../lib/types";
import { categoryLabel, formatKg } from "../../lib/format";

interface Props {
  insights: InsightsResponse;
}

export function AdvicePanel({ insights }: Props) {
  const originLabel = insights.source === "gemini" ? "AI-personalized" : "Smart rules";

  return (
    <section className="card" aria-labelledby="insights-heading">
      <h2 id="insights-heading">
        Personalized insights{" "}
        <span className="badge" title={`Generated by: ${originLabel}`}>
          {originLabel}
        </span>
      </h2>

      <p>{insights.summary}</p>

      <h3>Recommended actions</h3>
      <ul className="plain-list">
        {insights.recommendations.map((rec, i) => (
          <li className="recommendation" key={`${rec.category}-${i}`}>
            <strong>{categoryLabel(rec.category)}:</strong> {rec.action}
            <div className="saving">
              Potential saving: {formatKg(rec.estimated_annual_savings_kg)} CO₂e / year
            </div>
          </li>
        ))}
      </ul>
    </section>
  );
}
